variables:
  UV_VERSION: 0.5
  PYTHON_VERSION: 3.12
  BASE_LAYER: bookworm-slim
  UV_LINK_MODE: copy

ruff:
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  variables:
    UV_CACHE_DIR: .uv-cache
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - uv pip install --system ruff
    - uv cache prune --ci
    - ruff check --output-format gitlab
    - ruff format --check

pages:
  image: alpine:latest
  script:
    - mkdir -p public
    - find . -mindepth 1 -maxdepth 1 ! -name public -exec cp -r {} public/ \;
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
