name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linting:
    name: Linting
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: black, command: black . --check}
          - {name: flake8, command: flake8 .}
          - {name: isort, command: isort . --check}
          - {name: pylint, command: 'pylint . --evaluation "0 if fatal else max(0, 10 - error - warning)"'}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black flake8 isort pylint

      - name: Run ${{ matrix.name }}
        run: python -m ${{ matrix.command }}
